MODEL:
  VID:
    METHOD: "afgn"
    ROI_BOX_HEAD:
      ATTENTION:
        ENABLE: True
  META_ARCHITECTURE: "GeneralizedRCNNAFGN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "AFGNFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("VID_train_15frames",)  #"DET_train_30classes"
  TEST: ("VID_val_videos",)
