MODEL:
  VID:
    ENABLE: True
  RPN:
    ANCHOR_SIZES: (64, 128, 256, 512)
    PRE_NMS_TOP_N_TRAIN: 6000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 300
    POST_NMS_TOP_N_TEST: 300
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 128
    SCORE_THRESH: 0.001
    NMS: 0.5
    DETECTIONS_PER_IMG: 300
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 7
  RESNETS:
    RES5_DILATION: 2
INPUT:
  MIN_SIZE_TRAIN: (400,)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 400
  MAX_SIZE_TEST: 800
DATASETS:
  TRAIN: ("VID_train_15frames",) #"DET_train_30classes","VID_train_15frames"
  TEST: ("VID_val_frames",)
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (15000, )
  MAX_ITER: 20000
  IMS_PER_BATCH: 1
  WARMUP_ITERS: 500
TEST:
  IMS_PER_BATCH: 1
  DETECTIONS_PER_IMG: 300